"""primeiro acesso e autorizacao do responsavel

Revision ID: 15bb330defa5
Revises: 1fa9dfb0eb4d
Create Date: 2026-08-13 17:34:50.598856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Os modelos usam tipos do SQLModel (AutoString); o autogenerate os referencia
# nas migrations, entao o import precisa existir aqui.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15bb330defa5'
down_revision: Union[str, Sequence[str], None] = '1fa9dfb0eb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primeiro_acesso_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('autorizacao_responsavel_em', sa.DateTime(), nullable=True))

    # Backfill: quem ja aceitou os termos ate aqui so podia ter feito isso no
    # proprio primeiro acesso — o aceite pelo personal nasce nesta mesma versao.
    # Sem esta linha, todo aluno que ja assumiu a conta voltaria a ser editavel
    # pelo personal, silenciosamente.
    op.execute(
        "UPDATE usuario SET primeiro_acesso_em = termos_aceitos_em "
        "WHERE papel = 'ALUNO' AND aceitou_termos = 1 "
        "AND termos_aceitos_em IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('autorizacao_responsavel_em')
        batch_op.drop_column('primeiro_acesso_em')

    # ### end Alembic commands ###
