"""arquivar treino e dieta

Revision ID: 477fd8978d56
Revises: 15bb330defa5
Create Date: 2026-08-14 00:11:08.104974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Os modelos usam tipos do SQLModel (AutoString); o autogenerate os referencia
# nas migrations, entao o import precisa existir aqui.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '477fd8978d56'
down_revision: Union[str, Sequence[str], None] = '15bb330defa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.drop_column('arquivado_em')

    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.drop_column('arquivado_em')

    # ### end Alembic commands ###
