"""esquema inicial

Revision ID: 90d28405102b
Revises: 
Create Date: 2026-08-11 23:37:36.407908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Os modelos usam tipos do SQLModel (AutoString); o autogenerate os referencia
# nas migrations, entao o import precisa existir aqui.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90d28405102b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('papel', sa.Enum('PERSONAL', 'ALUNO', name='papel'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('objetivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('avaliacao',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('percentual_gordura', sa.Float(), nullable=True),
    sa.Column('massa_muscular_kg', sa.Float(), nullable=True),
    sa.Column('cintura_cm', sa.Float(), nullable=True),
    sa.Column('quadril_cm', sa.Float(), nullable=True),
    sa.Column('braco_cm', sa.Float(), nullable=True),
    sa.Column('coxa_cm', sa.Float(), nullable=True),
    sa.Column('torax_cm', sa.Float(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fotos', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacao_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('dieta',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calorias', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dia_semana', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('TREINO', 'AVALIACAO', 'RETORNO', name='tipoagendamento'), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamento_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('treinoexercicio',
    sa.Column('exercicio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treinoexercicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treinoexercicio_treino_id'), ['treino_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treinoexercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treinoexercicio_treino_id'))

    op.drop_table('treinoexercicio')
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamento_aluno_id'))

    op.drop_table('agendamento')
    op.drop_table('treino')
    op.drop_table('dieta')
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacao_aluno_id'))

    op.drop_table('avaliacao')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
