"""token de acesso para recuperacao e convite

Revision ID: cfef22d95bfd
Revises: 0f684accd538
Create Date: 2026-08-13 12:53:43.692251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Os modelos usam tipos do SQLModel (AutoString); o autogenerate os referencia
# nas migrations, entao o import precisa existir aqui.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfef22d95bfd'
down_revision: Union[str, Sequence[str], None] = '0f684accd538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokendeacesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('finalidade', sa.Enum('RECUPERACAO', 'CONVITE', name='finalidadedotoken'), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokendeacesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokendeacesso_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokendeacesso_usuario_id'), ['usuario_id'], unique=False)

    # O autogenerate queria dropar ix_sessaotreino_aluno_data aqui. E o indice
    # composto (aluno_id, data) criado a mao, que serve a consulta da semana e do
    # calendario — ele nao "sobrou", faltava estar declarado no modelo. Foi para
    # o __table_args__ de SessaoTreino, e o drop saiu daqui.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokendeacesso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokendeacesso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tokendeacesso_token_hash'))

    op.drop_table('tokendeacesso')
    # ### end Alembic commands ###
